### ISSUE TITLE
NGenetzky tracks progress on GitHub Flow

### ISSUE THREAD

**Issue by NGenetzky** [githubteacher/developers-july-PM#78]
### Master Branch

Should only contain merges with feature branches.

### Feature Branch

Branch that can be experimented or developed on.

### Commit

Snapshot of the project at a moment in time.

### Pull Request

A pull request is a request to consider merging the feature branch into master.
Other collaborators can comment on the work done.

## TODO list for Github Flow

- [ ] Create a branch
- [ ] Add a commit
- [ ] open a pull request
- [ ] collarborate and peer review of our contribution
- [ ] additional commits
- [ ] merge when we receive a thumbs-up
